Add json check, remove trailing newline and do not send empty messages
parrot-com/kaldi pull request #4
Opened 2020-10-21 11:44 UTC by jonaskratochvil

2020-10-21 14:08 UTC, tomassykora requested changes
These are probably just minor issues or only questions making sure everything works fine.

2020-10-21 14:08 UTC, tomassykora commented on src/online2bin/online2-tcp-nnet3-decode-faster_word_timestamps.cc
> +  /* bool WriteLn(const std::string &msg, const std::string &eol = ""); // write line to accepted client */
Please just remove this line if it's tested and we're not planning to return to the original code. Letting comments in the code is a bad practise which can mislead developers in the future. (Unless there's a good reason for it.)

2020-10-21 14:08 UTC, tomassykora commented on src/online2bin/online2-tcp-nnet3-decode-faster_word_timestamps.cc
> +                  if (jv) {
What happens when jv is false (meaning probably that the current_hypothesis is not a valid json)? Is is ok to not have the else branch here?

2020-10-21 14:08 UTC, tomassykora commented on src/online2bin/online2-tcp-nnet3-decode-faster_word_timestamps.cc
> +                {
This empty else branch seems not ok. Why is it empty here? There shouldn't be any if that's the intension or leave an explanatory comment.

2020-10-21 14:08 UTC, tomassykora commented on src/online2bin/online2-tcp-nnet3-decode-faster_word_timestamps.cc
> +              message.erase(std::prev(message.end()));
Just checking - doesn't it fail if it tries to erase an empty message?

2020-10-21 14:08 UTC, tomassykora commented on src/online2bin/online2-tcp-nnet3-decode-faster_word_timestamps.cc
> +              if (jv) {
Same question as above in the exactly same condition code.

2020-10-21 14:08 UTC, tomassykora commented on src/online2bin/online2-tcp-nnet3-decode-faster_word_timestamps.cc
> +                bool jv = json::accept(global_message);
Same as above. Also please fix the indents (also in other places of the file).

2020-10-22 06:08 UTC, jonaskratochvil commented on src/online2bin/online2-tcp-nnet3-decode-faster_word_timestamps.cc
> +  /* bool WriteLn(const std::string &msg, const std::string &eol = ""); // write line to accepted client */
Agree, I've removed this comment.

2020-10-22 06:11 UTC, jonaskratochvil commented on src/online2bin/online2-tcp-nnet3-decode-faster_word_timestamps.cc
> +              message.erase(std::prev(message.end()));
This will never happen as it is inside if (!message.empty()) block so the message is always non-empty when this line is reached.

2020-10-22 06:21 UTC, jonaskratochvil commented on src/online2bin/online2-tcp-nnet3-decode-faster_word_timestamps.cc
> +                {
This is now removed

2020-10-22 06:22 UTC, jonaskratochvil commented on src/online2bin/online2-tcp-nnet3-decode-faster_word_timestamps.cc
> +                  if (jv) {
I've added else statement which will make the server output warning when invalid json is encountered. This could be helpful for debugging.

2020-10-22 07:37 UTC, tomassykora approved these changes

2020-10-22 07:44 UTC, merged